%\VignetteIndexEntry{CopyNumber450kData User's Guide}
\newcommand{\Rcode}[1]{{\texttt{#1}}}
\newcommand{\Rpackage}[1]{\textsf{#1}}
\newcommand{\software}[1]{\textsf{#1}}
\newcommand{\R}{\software{R}}

\documentclass[12pt]{article}

\usepackage[utf8]{inputenc}
\usepackage{authblk}

\title{The CopyNumber450kData User's Guide:\\Normal controls for
the CopyNumber450k package}
\author[1,3]{Simon Papillon-Cavanagh}
\author[2]{Jean-Philippe Fortin}
\author[3]{Nicolas De Jay}
\affil[1]{McGill University and Genome Quebec Innovation Centre, Montreal, QC, Canada}
\affil[2]{Department of Biostatistics, Johns Hopkins Bloomberg School of Public
Health, Baltimore, MD, USA}
\affil[3]{Department of Human Genetics, McGill University, Montreal, QC, Canada}
\SweaveOpts{highlight=TRUE, tidy=TRUE, keep.space=TRUE, keep.blank.space=FALSE, keep.comment=TRUE}

<<setup,echo=FALSE,results=hide,eval=TRUE>>=
options(keep.source=TRUE)
@

\begin{document}

\maketitle
\tableofcontents

\section{Description}

In this package we provide a set of 52 control samples for the package
CopyNumber450k. The provided controls consist of material from healthy patients
with nominally no copy number abberations. Users of CopyNumber450k may use this
data package to complement their analysis.

\subsection{Example}
<<load>>=
require(CopyNumber450kData)
data(RGcontrolSetEx)
pData(RGcontrolSetEx)[,3:4]
@
\end{document}

